/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.liuxuan.UI.JIF_UIs;

import net.liuxuan.UI.DataHolder.DataHolder;
import net.liuxuan.UI.JIFUI;
import org.apache.mina.transport.serial.SerialAddress;

/**
 *
 * @author Moses
 */
public class JIF_SerialSetWindow extends JIFUI {

    private static JIF_SerialSetWindow myInstance; //thisJFrame singleton

    public static JIF_SerialSetWindow getInstance(DataHolder _datas) {
        if (myInstance == null) {
            myInstance = new JIF_SerialSetWindow();
        }
        myInstance.datas = _datas;
        return myInstance;
    }

    /**
     * Creates new form JF_SerialSet
     */
    private JIF_SerialSetWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_comportset2 = new javax.swing.JPanel();
        jLabel_ComPort2 = new javax.swing.JLabel();
        jComboBox_ComPort2 = new javax.swing.JComboBox();
        jLabel_BaudRate2 = new javax.swing.JLabel();
        jComboBox_BaudRate2 = new javax.swing.JComboBox();
        jCheckBox_isuse2 = new javax.swing.JCheckBox();
        jPanel_comportset1 = new javax.swing.JPanel();
        jLabel_ComPort1 = new javax.swing.JLabel();
        jComboBox_ComPort1 = new javax.swing.JComboBox();
        jLabel_BaudRate1 = new javax.swing.JLabel();
        jComboBox_BaudRate1 = new javax.swing.JComboBox();
        jCheckBox_isuse1 = new javax.swing.JCheckBox();
        jButton_ok = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("串口设置");

        jPanel_comportset2.setBorder(javax.swing.BorderFactory.createTitledBorder("串口2设置"));

        jLabel_ComPort2.setText("端口设置:");

        jComboBox_ComPort2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18", "COM19", "COM20", "COM21", "COM22", "COM23", "COM24", "COM25", "COM26", "COM27", "COM28", "COM29", "COM30", "COM31", "COM32" }));
        jComboBox_ComPort2.setSelectedIndex(1);
        jComboBox_ComPort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ComPort2ActionPerformed(evt);
            }
        });

        jLabel_BaudRate2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_BaudRate2.setText("速率:");

        jComboBox_BaudRate2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "43000", "56000", "57600", "115200" }));
        jComboBox_BaudRate2.setSelectedIndex(6);

        jCheckBox_isuse2.setSelected(true);
        jCheckBox_isuse2.setText("启用");
        jCheckBox_isuse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isuse2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_comportset2Layout = new javax.swing.GroupLayout(jPanel_comportset2);
        jPanel_comportset2.setLayout(jPanel_comportset2Layout);
        jPanel_comportset2Layout.setHorizontalGroup(
            jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_comportset2Layout.createSequentialGroup()
                .addGroup(jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_ComPort2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_BaudRate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_ComPort2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_BaudRate2, 0, 101, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(jPanel_comportset2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_isuse2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_comportset2Layout.setVerticalGroup(
            jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset2Layout.createSequentialGroup()
                .addComponent(jCheckBox_isuse2)
                .addGap(9, 9, 9)
                .addGroup(jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ComPort2)
                    .addComponent(jComboBox_ComPort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BaudRate2)
                    .addComponent(jComboBox_BaudRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_comportset1.setBorder(javax.swing.BorderFactory.createTitledBorder("串口1设置"));

        jLabel_ComPort1.setText("端口设置:");

        jComboBox_ComPort1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18", "COM19", "COM20", "COM21", "COM22", "COM23", "COM24", "COM25", "COM26", "COM27", "COM28", "COM29", "COM30", "COM31", "COM32" }));
        jComboBox_ComPort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ComPort1ActionPerformed(evt);
            }
        });

        jLabel_BaudRate1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_BaudRate1.setText("速率:");

        jComboBox_BaudRate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "43000", "56000", "57600", "115200" }));
        jComboBox_BaudRate1.setSelectedIndex(6);

        jCheckBox_isuse1.setSelected(true);
        jCheckBox_isuse1.setText("启用");
        jCheckBox_isuse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_isuse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_comportset1Layout = new javax.swing.GroupLayout(jPanel_comportset1);
        jPanel_comportset1.setLayout(jPanel_comportset1Layout);
        jPanel_comportset1Layout.setHorizontalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                        .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_ComPort1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_BaudRate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_BaudRate1, 0, 101, Short.MAX_VALUE)
                            .addComponent(jComboBox_ComPort1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jCheckBox_isuse1))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel_comportset1Layout.setVerticalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                .addComponent(jCheckBox_isuse1)
                .addGap(10, 10, 10)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ComPort1)
                    .addComponent(jComboBox_ComPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BaudRate1)
                    .addComponent(jComboBox_BaudRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jButton_ok.setText("设定");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_comportset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_comportset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_comportset2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_comportset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton_ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ComPort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ComPort2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ComPort2ActionPerformed

    private void jComboBox_ComPort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ComPort1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ComPort1ActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // TODO add your handling code here:
        int ibaudrate = Integer.parseInt((String) jComboBox_BaudRate1.getSelectedItem());
        String port = (String) jComboBox_ComPort1.getSelectedItem();
        SerialAddress portAddress1 = new SerialAddress(port, ibaudrate, SerialAddress.DataBits.DATABITS_8, SerialAddress.StopBits.BITS_1, SerialAddress.Parity.NONE,
                SerialAddress.FlowControl.NONE);

        datas.put(Comm1str, portAddress1);//放入公共变量

        ibaudrate = Integer.parseInt((String) jComboBox_BaudRate2.getSelectedItem());
        port = (String) jComboBox_ComPort2.getSelectedItem();
        SerialAddress portAddress2 = new SerialAddress(port, ibaudrate, SerialAddress.DataBits.DATABITS_8, SerialAddress.StopBits.BITS_1, SerialAddress.Parity.NONE,
                SerialAddress.FlowControl.NONE);
        datas.put(Comm2str, portAddress2);//放入公共变量

        datas.put(Comm1str_enable, jCheckBox_isuse1.isSelected());//放入公共变量
        datas.put(Comm2str_enable, jCheckBox_isuse2.isSelected());//放入公共变量
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jCheckBox_isuse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_isuse1ActionPerformed
        comm1enable(jCheckBox_isuse1.isSelected());
        if (jCheckBox_isuse1.isSelected()) {
//           System.out.println("选中");

        } else {
//           System.out.println("未选中");
        }

    }//GEN-LAST:event_jCheckBox_isuse1ActionPerformed

    private void jCheckBox_isuse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_isuse2ActionPerformed
        comm2enable(jCheckBox_isuse2.isSelected());
    }//GEN-LAST:event_jCheckBox_isuse2ActionPerformed

    private void comm1enable(boolean enable) {
        jComboBox_BaudRate1.setEnabled(enable);
        jComboBox_ComPort1.setEnabled(enable);
    }

    private void comm2enable(boolean enable) {
        jComboBox_BaudRate2.setEnabled(enable);
        jComboBox_ComPort2.setEnabled(enable);
    }

    public void init() {
        //读取当前串口数据
        Boolean comm1_enable = (Boolean) datas.get(Comm1str_enable);
        Boolean comm2_enable = (Boolean) datas.get(Comm2str_enable);
        SerialAddress portAddress1 = (SerialAddress) datas.get(Comm1str);
        SerialAddress portAddress2 = (SerialAddress) datas.get(Comm2str);
        if (portAddress1 != null) {
            jComboBox_BaudRate1.setSelectedItem("" + portAddress1.getBauds());
            jComboBox_ComPort1.setSelectedItem(portAddress1.getName());
        }
        if (portAddress2 != null) {
            jComboBox_BaudRate2.setSelectedItem("" + portAddress2.getBauds());
            jComboBox_ComPort2.setSelectedItem(portAddress2.getName());
        }
        if (comm1_enable != null) {
            comm1enable(comm1_enable);
            jCheckBox_isuse1.setEnabled(comm1_enable);
        }
        if (comm2_enable != null) {
            comm2enable(comm2_enable);
            jCheckBox_isuse2.setEnabled(comm2_enable);
        }
    }

    private static final String Comm1str = "comm1";
    private static final String Comm1str_enable = "comm1_enable";
    private static final String Comm2str = "comm2";
    private static final String Comm2str_enable = "comm2_enable";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ok;
    private javax.swing.JCheckBox jCheckBox_isuse1;
    private javax.swing.JCheckBox jCheckBox_isuse2;
    private javax.swing.JComboBox jComboBox_BaudRate1;
    private javax.swing.JComboBox jComboBox_BaudRate2;
    private javax.swing.JComboBox jComboBox_ComPort1;
    private javax.swing.JComboBox jComboBox_ComPort2;
    private javax.swing.JLabel jLabel_BaudRate1;
    private javax.swing.JLabel jLabel_BaudRate2;
    private javax.swing.JLabel jLabel_ComPort1;
    private javax.swing.JLabel jLabel_ComPort2;
    private javax.swing.JPanel jPanel_comportset1;
    private javax.swing.JPanel jPanel_comportset2;
    // End of variables declaration//GEN-END:variables

}
