/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.liuxuan.device.serialconnector;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.liuxuan.device.base.RS232Connector;
import net.liuxuan.device.bridge.codec.BridgeProtocolCodecFactory;
import net.liuxuan.device.bridge.handler.BridgeHandler;
import org.apache.mina.core.RuntimeIoException;
import org.apache.mina.core.service.IoHandlerAdapter;
import org.apache.mina.filter.codec.ProtocolCodecFilter;
import org.apache.mina.filter.logging.LoggingFilter;
import org.apache.mina.transport.serial.SerialAddress;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Moses
 */
public class SerialConnector extends javax.swing.JFrame {

    /**
     * Creates new form SerialConnector
     */
    public SerialConnector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_All = new javax.swing.JTabbedPane();
        jPanel_main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_SerialSet = new javax.swing.JPanel();
        jPanel_comportset2 = new javax.swing.JPanel();
        jLabel_ComPort2 = new javax.swing.JLabel();
        jComboBox_ComPort2 = new javax.swing.JComboBox();
        jLabel_BaudRate2 = new javax.swing.JLabel();
        jComboBox_BaudRate2 = new javax.swing.JComboBox();
        jPanel_comportset1 = new javax.swing.JPanel();
        jLabel_ComPort1 = new javax.swing.JLabel();
        jComboBox_ComPort1 = new javax.swing.JComboBox();
        jLabel_BaudRate1 = new javax.swing.JLabel();
        jComboBox_BaudRate1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton_Start = new javax.swing.JToggleButton();
        jPanel_output = new javax.swing.JPanel();
        jScrollPane_output = new javax.swing.JScrollPane();
        jTextArea_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("串口转发适配工具");

        jLabel2.setText("从一号口到二号口，数据进行转发中介");

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane_All.addTab("串口转发", jPanel_main);

        jPanel_SerialSet.setBorder(javax.swing.BorderFactory.createTitledBorder("设置"));

        jPanel_comportset2.setBorder(javax.swing.BorderFactory.createTitledBorder("串口2设置"));

        jLabel_ComPort2.setText("端口设置");

        jComboBox_ComPort2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18", "COM19", "COM20", "COM21", "COM22", "COM23", "COM24", "COM25", "COM26", "COM27", "COM28", "COM29", "COM30", "COM31", "COM32" }));
        jComboBox_ComPort2.setSelectedIndex(1);
        jComboBox_ComPort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ComPort2ActionPerformed(evt);
            }
        });

        jLabel_BaudRate2.setText("速率");

        jComboBox_BaudRate2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "43000", "56000", "57600", "115200" }));
        jComboBox_BaudRate2.setSelectedIndex(6);

        javax.swing.GroupLayout jPanel_comportset2Layout = new javax.swing.GroupLayout(jPanel_comportset2);
        jPanel_comportset2.setLayout(jPanel_comportset2Layout);
        jPanel_comportset2Layout.setHorizontalGroup(
            jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset2Layout.createSequentialGroup()
                .addComponent(jLabel_ComPort2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ComPort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BaudRate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_BaudRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_comportset2Layout.setVerticalGroup(
            jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_ComPort2)
                .addComponent(jComboBox_ComPort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_BaudRate2)
                .addComponent(jComboBox_BaudRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_comportset1.setBorder(javax.swing.BorderFactory.createTitledBorder("串口1设置"));

        jLabel_ComPort1.setText("端口设置");

        jComboBox_ComPort1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18", "COM19", "COM20", "COM21", "COM22", "COM23", "COM24", "COM25", "COM26", "COM27", "COM28", "COM29", "COM30", "COM31", "COM32" }));
        jComboBox_ComPort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ComPort1ActionPerformed(evt);
            }
        });

        jLabel_BaudRate1.setText("速率");

        jComboBox_BaudRate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "43000", "56000", "57600", "115200" }));
        jComboBox_BaudRate1.setSelectedIndex(6);

        javax.swing.GroupLayout jPanel_comportset1Layout = new javax.swing.GroupLayout(jPanel_comportset1);
        jPanel_comportset1.setLayout(jPanel_comportset1Layout);
        jPanel_comportset1Layout.setHorizontalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createSequentialGroup()
                .addComponent(jLabel_ComPort1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ComPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BaudRate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_BaudRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_comportset1Layout.setVerticalGroup(
            jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comportset1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_ComPort1)
                .addComponent(jComboBox_ComPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_BaudRate1)
                .addComponent(jComboBox_BaudRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel_SerialSetLayout = new javax.swing.GroupLayout(jPanel_SerialSet);
        jPanel_SerialSet.setLayout(jPanel_SerialSetLayout);
        jPanel_SerialSetLayout.setHorizontalGroup(
            jPanel_SerialSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SerialSetLayout.createSequentialGroup()
                .addComponent(jPanel_comportset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_comportset2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(314, 314, 314))
        );
        jPanel_SerialSetLayout.setVerticalGroup(
            jPanel_SerialSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SerialSetLayout.createSequentialGroup()
                .addGroup(jPanel_SerialSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_comportset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_comportset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("操作"));

        jToggleButton_Start.setText("开始");
        jToggleButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton_Start)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton_Start)
        );

        jPanel_output.setBorder(javax.swing.BorderFactory.createTitledBorder("信息输出区"));

        jTextArea_output.setColumns(20);
        jTextArea_output.setRows(5);
        jScrollPane_output.setViewportView(jTextArea_output);

        javax.swing.GroupLayout jPanel_outputLayout = new javax.swing.GroupLayout(jPanel_output);
        jPanel_output.setLayout(jPanel_outputLayout);
        jPanel_outputLayout.setHorizontalGroup(
            jPanel_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_output)
        );
        jPanel_outputLayout.setVerticalGroup(
            jPanel_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_output, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane_All)
                    .addComponent(jPanel_SerialSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_All)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SerialSet, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ComPort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ComPort2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ComPort2ActionPerformed

    private void jComboBox_ComPort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ComPort1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ComPort1ActionPerformed

    private void jToggleButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_StartActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        portAddress1 = getserialport1();
        portAddress2 = getserialport2();

        if (handler1 == null) {
            handler1 = new BridgeHandler();
            ((BridgeHandler) handler1).name = "1";
        }
        if (handler2 == null) {
            handler2 = new BridgeHandler();
            ((BridgeHandler) handler2).name = "2";
        }
        if (receiver1 != null) {
            receiver1.endListen();
        }
        if (receiver2 != null) {
            receiver2.endListen();
        }

        receiver1 = new RS232Connector(handler1, portAddress1);
        receiver2 = new RS232Connector(handler2, portAddress2);

        ((BridgeHandler) handler1).setDest(receiver2);
        ((BridgeHandler) handler2).setDest(receiver1);

//        receiver1.addFilter("logger", new LoggingFilter());
        receiver1.addFilter("codec", new ProtocolCodecFilter(new BridgeProtocolCodecFactory()));    // 设置编码过滤器
//        receiver2.addFilter("logger", new LoggingFilter());
        receiver2.addFilter("codec", new ProtocolCodecFilter(new BridgeProtocolCodecFactory()));    // 设置编码过滤器
        if (jToggleButton_Start.isSelected()) {
            try {
                receiver1.startListen();
                receiver2.startListen();
            } catch (RuntimeIoException e) {
                System.out.println("串口打开失败");
            }

            if (((BridgeHandler) handler1).outfile == null) {
                File path = new File("c:\\logs\\");
                path.mkdirs();
                ((BridgeHandler) handler1).outfile = new File("c:\\logs\\Out1-" + sdf.format(new Date()) + ".txt");
                ((BridgeHandler) handler2).outfile = new File("c:\\logs\\Out2-" + sdf.format(new Date()) + ".txt");
            }
            ((BridgeHandler) handler1).initfilelog();
            ((BridgeHandler) handler2).initfilelog();
            jToggleButton_Start.setText("关闭");
        } else {
            receiver1.endListen();
            receiver2.endListen();
            ((BridgeHandler) handler1).teminatefilelog();
            ((BridgeHandler) handler2).teminatefilelog();

            jToggleButton_Start.setText("开始");
        }

        java.util.logging.Logger.getLogger(SerialConnector.class.getName()).log(java.util.logging.Level.SEVERE, "XXXXX");
    }//GEN-LAST:event_jToggleButton_StartActionPerformed

    // Variables declaration
    SerialAddress portAddress1;//input port
    SerialAddress portAddress2;//output port
    IoHandlerAdapter handler1;
    IoHandlerAdapter handler2;
    RS232Connector receiver1 = null;
    RS232Connector receiver2 = null;
    private static final Logger log = LoggerFactory.getLogger(SerialConnector.class);

    // End of variables declaration   
    private SerialAddress getserialport1() {
        int ibaudrate = Integer.parseInt((String) jComboBox_BaudRate1.getSelectedItem());
        String port = (String) jComboBox_ComPort1.getSelectedItem();
        portAddress1 = new SerialAddress(port, ibaudrate, SerialAddress.DataBits.DATABITS_8, SerialAddress.StopBits.BITS_1, SerialAddress.Parity.NONE,
                SerialAddress.FlowControl.NONE);
        log.debug("port1:{}", portAddress1.toString());
        return portAddress1;
    }

    private SerialAddress getserialport2() {
        int ibaudrate = Integer.parseInt((String) jComboBox_BaudRate2.getSelectedItem());
        String port = (String) jComboBox_ComPort2.getSelectedItem();
        portAddress2 = new SerialAddress(port, ibaudrate, SerialAddress.DataBits.DATABITS_8, SerialAddress.StopBits.BITS_1, SerialAddress.Parity.NONE,
                SerialAddress.FlowControl.NONE);
        log.debug("port2:{}", portAddress1.toString());
        return portAddress2;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SerialConnector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SerialConnector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SerialConnector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SerialConnector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SerialConnector().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_BaudRate1;
    private javax.swing.JComboBox jComboBox_BaudRate2;
    private javax.swing.JComboBox jComboBox_ComPort1;
    private javax.swing.JComboBox jComboBox_ComPort2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_BaudRate1;
    private javax.swing.JLabel jLabel_BaudRate2;
    private javax.swing.JLabel jLabel_ComPort1;
    private javax.swing.JLabel jLabel_ComPort2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_SerialSet;
    private javax.swing.JPanel jPanel_comportset1;
    private javax.swing.JPanel jPanel_comportset2;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_output;
    private javax.swing.JScrollPane jScrollPane_output;
    private javax.swing.JTabbedPane jTabbedPane_All;
    private javax.swing.JTextArea jTextArea_output;
    private javax.swing.JToggleButton jToggleButton_Start;
    // End of variables declaration//GEN-END:variables
}
