/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.liuxuan.device.VACVBS;

import javax.swing.JFormattedTextField;

/**
 *
 * @author Moses
 */
public class VACcompute extends javax.swing.JFrame {

    /**
     * Creates new form VBScompute
     */
    public VACcompute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFormattedTextField_VAC_d = new javax.swing.JFormattedTextField();
        jLabel_VAC_d = new javax.swing.JLabel();
        jButton_VAC_compute = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jFormattedTextField_VAC_V = new javax.swing.JFormattedTextField();
        jLabel_VAC_V = new javax.swing.JLabel();
        jLabel_VAC_S = new javax.swing.JLabel();
        jFormattedTextField_VAC_S = new javax.swing.JFormattedTextField();
        jLabel_VAC_T = new javax.swing.JLabel();
        jFormattedTextField_VAC_T = new javax.swing.JFormattedTextField();
        jLabel_VAC_P0 = new javax.swing.JLabel();
        jFormattedTextField_VAC_P0 = new javax.swing.JFormattedTextField();
        jFormattedTextField_VAC_P1 = new javax.swing.JFormattedTextField();
        jLabel_VAC_P1 = new javax.swing.JLabel();
        jFormattedTextField_VAC_P2 = new javax.swing.JFormattedTextField();
        jLabel_VAC_P2 = new javax.swing.JLabel();
        jLabel_VAC_deltaT = new javax.swing.JLabel();
        jFormattedTextField_VAC_deltaT = new javax.swing.JFormattedTextField();
        jLabel_VAC_deltaPstart = new javax.swing.JLabel();
        jFormattedTextField_VAC_deltaPstart = new javax.swing.JFormattedTextField();
        jFormattedTextField_VAC_deltaPend = new javax.swing.JFormattedTextField();
        jLabel_VAC_deltaPend = new javax.swing.JLabel();
        jFormattedTextField_VAC_n = new javax.swing.JFormattedTextField();
        jLabel_VAC_n = new javax.swing.JLabel();
        jLabel_VAC_T0 = new javax.swing.JLabel();
        jFormattedTextField_VAC_T0 = new javax.swing.JFormattedTextField();
        jRadioButton_vac_7210 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jFormattedTextField_VAC_kuosanP1 = new javax.swing.JFormattedTextField();
        jLabel_VAC_kuosanP1 = new javax.swing.JLabel();
        jLabel_VAC_kuosanP2 = new javax.swing.JLabel();
        jFormattedTextField_VAC_kuosanP2 = new javax.swing.JFormattedTextField();
        jLabel_VAC_kuosanT1 = new javax.swing.JLabel();
        jFormattedTextField_VAC_kuosanT1 = new javax.swing.JFormattedTextField();
        jFormattedTextField_VAC_kuosanT2 = new javax.swing.JFormattedTextField();
        jLabel_VAC_kuosanT2 = new javax.swing.JLabel();
        jRadioButton_vac_7110 = new javax.swing.JRadioButton();
        jRadioButton_vac_7200 = new javax.swing.JRadioButton();
        jRadioButton_vac_7100 = new javax.swing.JRadioButton();
        jPanel_vac_other = new javax.swing.JPanel();
        jLabel_vac_FilmCalibration = new javax.swing.JLabel();
        jFormattedTextField_VAC_filmcali = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_output = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("渗透系数"));

        jFormattedTextField_VAC_d.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_d.setText("125");
        jFormattedTextField_VAC_d.setToolTipText("试样厚度");
        jFormattedTextField_VAC_d.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_dFocusGained(evt);
            }
        });

        jLabel_VAC_d.setText("d(μm)：");
        jLabel_VAC_d.setToolTipText("下腔体积");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_VAC_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField_VAC_d, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_d))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton_VAC_compute.setText("计算");
        jButton_VAC_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VAC_computeActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("常规参数"));

        jFormattedTextField_VAC_V.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        jFormattedTextField_VAC_V.setText("8.01");
        jFormattedTextField_VAC_V.setToolTipText("下腔体积");
        jFormattedTextField_VAC_V.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_VFocusGained(evt);
            }
        });

        jLabel_VAC_V.setText("V(ml)：");
        jLabel_VAC_V.setToolTipText("下腔体积");

        jLabel_VAC_S.setText("S(m2)：");
        jLabel_VAC_S.setToolTipText("测试面积");

        jFormattedTextField_VAC_S.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000000"))));
        jFormattedTextField_VAC_S.setText("0.003848");
        jFormattedTextField_VAC_S.setToolTipText("测试面积");
        jFormattedTextField_VAC_S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_SFocusGained(evt);
            }
        });

        jLabel_VAC_T.setText("T(℃)：");
        jLabel_VAC_T.setToolTipText("273.15");

        jFormattedTextField_VAC_T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_T.setText("25");
        jFormattedTextField_VAC_T.setToolTipText("273.15");
        jFormattedTextField_VAC_T.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_TFocusGained(evt);
            }
        });

        jLabel_VAC_P0.setText("P0(pa)：");
        jLabel_VAC_P0.setToolTipText("101300");

        jFormattedTextField_VAC_P0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        jFormattedTextField_VAC_P0.setText("101300");
        jFormattedTextField_VAC_P0.setToolTipText("101300");
        jFormattedTextField_VAC_P0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_P0FocusGained(evt);
            }
        });

        jFormattedTextField_VAC_P1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));
        jFormattedTextField_VAC_P1.setText("1");
        jFormattedTextField_VAC_P1.setToolTipText("高压腔压力");
        jFormattedTextField_VAC_P1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_P1FocusGained(evt);
            }
        });

        jLabel_VAC_P1.setText("P1(0.1MPa)：");
        jLabel_VAC_P1.setToolTipText("高压腔压力");

        jFormattedTextField_VAC_P2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));
        jFormattedTextField_VAC_P2.setText("0");
        jFormattedTextField_VAC_P2.setToolTipText("低压腔压力");
        jFormattedTextField_VAC_P2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_P2FocusGained(evt);
            }
        });

        jLabel_VAC_P2.setText("P2(0.1MPa)：");
        jLabel_VAC_P2.setToolTipText("低压腔压力");

        jLabel_VAC_deltaT.setText("Δt(s)：");
        jLabel_VAC_deltaT.setToolTipText("时间差");

        jFormattedTextField_VAC_deltaT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        jFormattedTextField_VAC_deltaT.setText("3600");
        jFormattedTextField_VAC_deltaT.setToolTipText("时间差");
        jFormattedTextField_VAC_deltaT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_deltaTFocusGained(evt);
            }
        });

        jLabel_VAC_deltaPstart.setText("ΔP_start(Pa)：");
        jLabel_VAC_deltaPstart.setToolTipText("初始压力");

        jFormattedTextField_VAC_deltaPstart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        jFormattedTextField_VAC_deltaPstart.setText("9");
        jFormattedTextField_VAC_deltaPstart.setToolTipText("初始压力");
        jFormattedTextField_VAC_deltaPstart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_deltaPstartFocusGained(evt);
            }
        });

        jFormattedTextField_VAC_deltaPend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        jFormattedTextField_VAC_deltaPend.setText("150");
        jFormattedTextField_VAC_deltaPend.setToolTipText("最后压力");
        jFormattedTextField_VAC_deltaPend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_deltaPendFocusGained(evt);
            }
        });

        jLabel_VAC_deltaPend.setText("ΔP_end(Pa)：");
        jLabel_VAC_deltaPend.setToolTipText("最后压力");

        jFormattedTextField_VAC_n.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_VAC_n.setText("3");
        jFormattedTextField_VAC_n.setToolTipText("试样件数");
        jFormattedTextField_VAC_n.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_nFocusGained(evt);
            }
        });

        jLabel_VAC_n.setText("n(件)：");
        jLabel_VAC_n.setToolTipText("下腔体积");

        jLabel_VAC_T0.setText("T0(K)：");
        jLabel_VAC_T0.setToolTipText("273.15");

        jFormattedTextField_VAC_T0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_T0.setText("273.15");
        jFormattedTextField_VAC_T0.setToolTipText("273.15");
        jFormattedTextField_VAC_T0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_T0FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_VAC_T0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_VAC_T0, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_VAC_V, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_S, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_T, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_P0, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_P1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_P2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_deltaT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_deltaPstart, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_deltaPend, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VAC_n, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField_VAC_V, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_S, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_P0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_P1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_P2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_deltaT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_deltaPstart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_deltaPend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_VAC_n, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_V))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_S))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_T))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_T0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_T0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_P0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_P0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_P1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_P2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_deltaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_deltaT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_deltaPstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_deltaPstart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_deltaPend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_deltaPend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_n)))
        );

        jRadioButton_vac_7210.setText("7210");
        jRadioButton_vac_7210.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_vac_7210ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("扩散系数"));

        jFormattedTextField_VAC_kuosanP1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_kuosanP1.setText("150");
        jFormattedTextField_VAC_kuosanP1.setToolTipText("最终压力");
        jFormattedTextField_VAC_kuosanP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_kuosanP1FocusGained(evt);
            }
        });

        jLabel_VAC_kuosanP1.setText("p1(Pa)：");
        jLabel_VAC_kuosanP1.setToolTipText("最终压力");

        jLabel_VAC_kuosanP2.setText("p2(Pa)：");
        jLabel_VAC_kuosanP2.setToolTipText("距离最后两个测试间隔压力");

        jFormattedTextField_VAC_kuosanP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_kuosanP2.setText("100");
        jFormattedTextField_VAC_kuosanP2.setToolTipText("距离最后两个测试间隔压力");
        jFormattedTextField_VAC_kuosanP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_kuosanP2FocusGained(evt);
            }
        });

        jLabel_VAC_kuosanT1.setText("t1(s)：");
        jLabel_VAC_kuosanT1.setToolTipText("最终时间");

        jFormattedTextField_VAC_kuosanT1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_kuosanT1.setText("7200");
        jFormattedTextField_VAC_kuosanT1.setToolTipText("S---------为计量管的截面积，单位为cm2");
        jFormattedTextField_VAC_kuosanT1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_kuosanT1FocusGained(evt);
            }
        });

        jFormattedTextField_VAC_kuosanT2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField_VAC_kuosanT2.setText("0");
        jFormattedTextField_VAC_kuosanT2.setToolTipText("S---------为计量管的截面积，单位为cm2");
        jFormattedTextField_VAC_kuosanT2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_kuosanT2FocusGained(evt);
            }
        });

        jLabel_VAC_kuosanT2.setText("t2(s)：");
        jLabel_VAC_kuosanT2.setToolTipText("距离最后两个测试间隔的时刻");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_VAC_kuosanP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_VAC_kuosanP1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_VAC_kuosanP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_VAC_kuosanP2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_VAC_kuosanT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_VAC_kuosanT1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_VAC_kuosanT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField_VAC_kuosanT2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_kuosanP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_kuosanP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_kuosanP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_kuosanP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_kuosanT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_kuosanT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_VAC_kuosanT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VAC_kuosanT2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton_vac_7110.setText("7110");
        jRadioButton_vac_7110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_vac_7110ActionPerformed(evt);
            }
        });

        jRadioButton_vac_7200.setText("7200");
        jRadioButton_vac_7200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_vac_7200ActionPerformed(evt);
            }
        });

        jRadioButton_vac_7100.setText("7100");
        jRadioButton_vac_7100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_vac_7100ActionPerformed(evt);
            }
        });

        jPanel_vac_other.setBorder(javax.swing.BorderFactory.createTitledBorder("其他"));

        jLabel_vac_FilmCalibration.setText("膜标定系数：");

        jFormattedTextField_VAC_filmcali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        jFormattedTextField_VAC_filmcali.setText("1");
        jFormattedTextField_VAC_filmcali.setToolTipText("最终压力");
        jFormattedTextField_VAC_filmcali.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_VAC_filmcaliFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel_vac_otherLayout = new javax.swing.GroupLayout(jPanel_vac_other);
        jPanel_vac_other.setLayout(jPanel_vac_otherLayout);
        jPanel_vac_otherLayout.setHorizontalGroup(
            jPanel_vac_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_vac_otherLayout.createSequentialGroup()
                .addComponent(jLabel_vac_FilmCalibration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField_VAC_filmcali))
        );
        jPanel_vac_otherLayout.setVerticalGroup(
            jPanel_vac_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_vac_otherLayout.createSequentialGroup()
                .addGroup(jPanel_vac_otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_vac_FilmCalibration)
                    .addComponent(jFormattedTextField_VAC_filmcali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTextArea_output.setColumns(20);
        jTextArea_output.setRows(5);
        jScrollPane2.setViewportView(jTextArea_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_vac_7210)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_vac_7200))
                            .addComponent(jButton_VAC_compute)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_vac_7110)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton_vac_7100))
                            .addComponent(jPanel_vac_other, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_vac_7210)
                            .addComponent(jRadioButton_vac_7200))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_vac_7110)
                            .addComponent(jRadioButton_vac_7100))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_vac_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_VAC_compute))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField_VAC_dFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_dFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_dFocusGained

    private void jButton_VAC_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VAC_computeActionPerformed
        double V = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_V);
        double S = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_S);
        double T = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_T);
        T += 273.15;
        double T0 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_T0);
        double P0 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_P0);
        double P1 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_P1);

        double P2 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_P2);

        double deltaT = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_deltaT);
        double deltaPstart = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_deltaPstart);
        double deltaPend = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_deltaPend);
        double n = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_n);
        double d = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_d);
        d = d / 10000;
        double kuosanp1 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_kuosanP1);
        double kuosanp2 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_kuosanP2);
        double kuosant1 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_kuosanT1);
        double kuosant2 = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_kuosanT2);
        double filmcali = getDoubleFromjFormattedTextField(jFormattedTextField_VAC_filmcali);

        double deltaP = deltaPend - deltaPstart;

        //O2GTR=（ΔP/Δt）•［V(/nS）］•［T0 / (P0T)］•［24 / (P1- P2)］

            double O2_GTR = (deltaP / (deltaT/3600)) * (V  / (n * S)) * (T0 / P0 / T) * (24 / (P1 - P2))*filmcali ;

            double O2_Pg = O2_GTR / 24 * d;//渗透系数

            double theta = (kuosant1 - kuosanp1 * ((kuosant1 - kuosant2) / (kuosanp1 - kuosanp2))) / 3600; //θ
            double O2_D = d * d / (6 * theta);//扩散系数

            double O2_S = O2_Pg / O2_D;//溶解度系数

            jTextArea_output.append(null);
            jTextArea_output.setText("透气量O2_GTR结果为：" + O2_GTR + "  cm3/m2·24h·0.1MPa");
            jTextArea_output.append(",透气量O2_GTR2000结果为：" + O2_GTR/101325 + "  cm3·cm/m2·d·Pa");
            jTextArea_output.append("\r\n渗透系数Pg结果为：" + O2_Pg + "  cm3·cm/m2·h·0.1MPa");

            jTextArea_output.append("\r\n扩散系数D结果为：" + O2_D + "  cm2/h，" + "   θ值为：" + theta);

            jTextArea_output.append("\r\n溶解度系数S结果为：" + O2_S + "  cm2/m2·0.1Mpa");
    }//GEN-LAST:event_jButton_VAC_computeActionPerformed

    private void jFormattedTextField_VAC_VFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_VFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_VFocusGained

    private void jFormattedTextField_VAC_SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_SFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_SFocusGained

    private void jFormattedTextField_VAC_TFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_TFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_TFocusGained

    private void jFormattedTextField_VAC_P0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_P0FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_P0FocusGained

    private void jFormattedTextField_VAC_P1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_P1FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_P1FocusGained

    private void jFormattedTextField_VAC_P2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_P2FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_P2FocusGained

    private void jFormattedTextField_VAC_deltaTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_deltaTFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_deltaTFocusGained

    private void jFormattedTextField_VAC_deltaPstartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_deltaPstartFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_deltaPstartFocusGained

    private void jFormattedTextField_VAC_deltaPendFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_deltaPendFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_deltaPendFocusGained

    private void jFormattedTextField_VAC_nFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_nFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_nFocusGained

    private void jFormattedTextField_VAC_T0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_T0FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_T0FocusGained

    private void jRadioButton_vac_7210ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_vac_7210ActionPerformed

        jFormattedTextField_VAC_V.setValue(11.166d);
        jFormattedTextField_VAC_S.setValue(0.003848d);
        jFormattedTextField_VAC_T.setValue(25d);
        jFormattedTextField_VAC_T0.setValue(273.15d);
        jFormattedTextField_VAC_P0.setValue(101300d);
        jFormattedTextField_VAC_P1.setValue(1d);
        jFormattedTextField_VAC_deltaT.setValue(3600d);
        jFormattedTextField_VAC_deltaPstart.setValue(9d);
        jFormattedTextField_VAC_deltaPend.setValue(150d);
        jFormattedTextField_VAC_n.setValue(1d);
        jFormattedTextField_VAC_d.setValue(125d);
        jFormattedTextField_VAC_kuosanP1.setValue(150d);
        jFormattedTextField_VAC_kuosanP2.setValue(100d);
        jFormattedTextField_VAC_kuosanT1.setValue(7200d);
        jFormattedTextField_VAC_kuosanT2.setValue(0d);

    }//GEN-LAST:event_jRadioButton_vac_7210ActionPerformed

    private void jFormattedTextField_VAC_kuosanP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_kuosanP1FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_kuosanP1FocusGained

    private void jFormattedTextField_VAC_kuosanP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_kuosanP2FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_kuosanP2FocusGained

    private void jFormattedTextField_VAC_kuosanT1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_kuosanT1FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_kuosanT1FocusGained

    private void jFormattedTextField_VAC_kuosanT2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_kuosanT2FocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_kuosanT2FocusGained

    private void jRadioButton_vac_7110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_vac_7110ActionPerformed
        jFormattedTextField_VAC_V.setValue(20.2389d);
        jFormattedTextField_VAC_S.setValue(0.002827d);
        jFormattedTextField_VAC_T.setValue(25d);
        jFormattedTextField_VAC_T0.setValue(273d);
        jFormattedTextField_VAC_P0.setValue(101325d);
        jFormattedTextField_VAC_P1.setValue(1.01000d);
        jFormattedTextField_VAC_P2.setValue(0.00000d);
        jFormattedTextField_VAC_deltaT.setValue(3600d);
        jFormattedTextField_VAC_deltaPstart.setValue(9d);
        jFormattedTextField_VAC_deltaPend.setValue(150d);
        jFormattedTextField_VAC_n.setValue(3d);
        jFormattedTextField_VAC_d.setValue(125d);
        jFormattedTextField_VAC_kuosanP1.setValue(150d);
        jFormattedTextField_VAC_kuosanP2.setValue(100d);
        jFormattedTextField_VAC_kuosanT1.setValue(7200d);
        jFormattedTextField_VAC_kuosanT2.setValue(0d);
    }//GEN-LAST:event_jRadioButton_vac_7110ActionPerformed

    private void jRadioButton_vac_7200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_vac_7200ActionPerformed
        jFormattedTextField_VAC_V.setValue(8.010d);
        jFormattedTextField_VAC_S.setValue(0.003848d);
        jFormattedTextField_VAC_T.setValue(25d);
        jFormattedTextField_VAC_T0.setValue(273.15d);
        jFormattedTextField_VAC_P0.setValue(101300d);
        jFormattedTextField_VAC_P1.setValue(1d);
        jFormattedTextField_VAC_P2.setValue(0d);
        jFormattedTextField_VAC_deltaT.setValue(3600d);
        jFormattedTextField_VAC_deltaPstart.setValue(9d);
        jFormattedTextField_VAC_deltaPend.setValue(150d);
        jFormattedTextField_VAC_n.setValue(3d);
        jFormattedTextField_VAC_d.setValue(125d);
        jFormattedTextField_VAC_kuosanP1.setValue(150d);
        jFormattedTextField_VAC_kuosanP2.setValue(100d);
        jFormattedTextField_VAC_kuosanT1.setValue(7200d);
        jFormattedTextField_VAC_kuosanT2.setValue(0d);
    }//GEN-LAST:event_jRadioButton_vac_7200ActionPerformed

    private void jRadioButton_vac_7100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_vac_7100ActionPerformed
        jFormattedTextField_VAC_V.setValue(8.01d);
        jFormattedTextField_VAC_S.setValue(0.003848d);
        jFormattedTextField_VAC_T.setValue(25d);
        jFormattedTextField_VAC_T0.setValue(273.15d);
        jFormattedTextField_VAC_P0.setValue(101300d);
        jFormattedTextField_VAC_P1.setValue(1d);
        jFormattedTextField_VAC_P2.setValue(0d);
        jFormattedTextField_VAC_deltaT.setValue(3600d);
        jFormattedTextField_VAC_deltaPstart.setValue(9d);
        jFormattedTextField_VAC_deltaPend.setValue(150d);
        jFormattedTextField_VAC_n.setValue(3d);
        jFormattedTextField_VAC_d.setValue(125d);
        jFormattedTextField_VAC_kuosanP1.setValue(150d);
        jFormattedTextField_VAC_kuosanP2.setValue(100d);
        jFormattedTextField_VAC_kuosanT1.setValue(7200d);
        jFormattedTextField_VAC_kuosanT2.setValue(0d);
    }//GEN-LAST:event_jRadioButton_vac_7100ActionPerformed

    private void jFormattedTextField_VAC_filmcaliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_VAC_filmcaliFocusGained
        ((JFormattedTextField) evt.getComponent()).setText(((JFormattedTextField) evt.getComponent()).getText());
        ((JFormattedTextField) evt.getComponent()).selectAll();
    }//GEN-LAST:event_jFormattedTextField_VAC_filmcaliFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VACcompute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VACcompute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VACcompute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VACcompute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VACcompute().setVisible(true);
            }
        });
    }
    
    private double getDoubleFromjFormattedTextField(JFormattedTextField jftf) throws NumberFormatException {
        double deltam;
        String sdeltam = jftf.getText();
        if (sdeltam == null || sdeltam.equals("")) {
            sdeltam = "0";
        }
        deltam = Double.parseDouble(sdeltam);
        return deltam;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_VAC_compute;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_P0;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_P1;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_P2;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_S;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_T;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_T0;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_V;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_d;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_deltaPend;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_deltaPstart;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_deltaT;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_filmcali;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_kuosanP1;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_kuosanP2;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_kuosanT1;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_kuosanT2;
    public javax.swing.JFormattedTextField jFormattedTextField_VAC_n;
    private javax.swing.JLabel jLabel_VAC_P0;
    private javax.swing.JLabel jLabel_VAC_P1;
    private javax.swing.JLabel jLabel_VAC_P2;
    private javax.swing.JLabel jLabel_VAC_S;
    private javax.swing.JLabel jLabel_VAC_T;
    private javax.swing.JLabel jLabel_VAC_T0;
    private javax.swing.JLabel jLabel_VAC_V;
    private javax.swing.JLabel jLabel_VAC_d;
    private javax.swing.JLabel jLabel_VAC_deltaPend;
    private javax.swing.JLabel jLabel_VAC_deltaPstart;
    private javax.swing.JLabel jLabel_VAC_deltaT;
    private javax.swing.JLabel jLabel_VAC_kuosanP1;
    private javax.swing.JLabel jLabel_VAC_kuosanP2;
    private javax.swing.JLabel jLabel_VAC_kuosanT1;
    private javax.swing.JLabel jLabel_VAC_kuosanT2;
    private javax.swing.JLabel jLabel_VAC_n;
    private javax.swing.JLabel jLabel_vac_FilmCalibration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_vac_other;
    private javax.swing.JRadioButton jRadioButton_vac_7100;
    private javax.swing.JRadioButton jRadioButton_vac_7110;
    private javax.swing.JRadioButton jRadioButton_vac_7200;
    private javax.swing.JRadioButton jRadioButton_vac_7210;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_output;
    // End of variables declaration//GEN-END:variables
}
